Update event-subscription-template.yaml: Attribute startsAt set optional, info and servers object
camaraproject/Commonalities pull request #267
Opened 2024-08-02 12:01 UTC by rartych

#### What type of PR is this?

* correction

#### What this PR does / why we need it:

Attribute startsAt is optional in [API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#resource-based-explicit-subscription), so it should be in [event subscription template file](https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml) .

Corrections made in `info` and `servers` object according to API Design Guidelines.

#### Which issue(s) this PR fixes:

Fixes #262 

#### Special notes for reviewers:

#### Changelog input

```
Attribute startsAt set optional, info and servers object corrected in event-subscription-template.yaml

```

2024-08-06 09:36 UTC, PedroDiez commented
@rartych initial comment. It is also needed to update https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#121-subscription

![image](https://github.com/user-attachments/assets/ca47442c-29e2-4969-b050-fb25d172a22c)

Suggestion:
"Date when the event subscription has started. This attribute must not be present in the POST request as it is provided by API server. It ONLY must be present in GET endpoints once the subscription is effectively operative/working."


CLARIFICATION about my comment: Avoiding the use of "ACTIVE" status wording as in MetaRelease v0.4 the umplementation of STATUS is optional

2024-08-06 11:37 UTC, rartych commented
As [Cloudevents Subscriptions OpenAPI](https://github.com/cloudevents/spec/blob/main/subscriptions/subscriptions-openapi.yaml) was used for the template, it defines 2 components: `SubscriptionRequest` for  POST request and `Subscription` present only in responses. [API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#121-subscription) - as you indicated - should be corrected, but I would prefer to do it with the final release, and possibly split the table into 2 tables for request and response parameters in the next version of Commonalities. It would be good to have the input from @bigludo7 for that.
My initial proposal for attribute description:
`"Date when the event subscription has started. This attribute must be present in the response when subscription creation process is completed"`


The rationale for changing `startsAt` to optional in `Subscription` component is the asynchronous subscription creation , when its starting moment is not known yet (#262). It should be decided by subprojects if the asynchronous case is covered by the API.

2024-08-06 14:21 UTC, Kevsy requested changes
Line 626: `terminationDescription` needs a `description` to avoid a spectral linter warning

2024-08-06 14:24 UTC, Kevsy commented
Line 453: Spectral warning, " `Event-typeNotification` should be pascal case (UpperCamelCase)"

2024-08-07 09:30 UTC, PedroDiez commented
> As [Cloudevents Subscriptions OpenAPI](https://github.com/cloudevents/spec/blob/main/subscriptions/subscriptions-openapi.yaml) was used for the template, it defines 2 components: `SubscriptionRequest` for POST request and `Subscription` present only in responses. [API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#121-subscription) - as you indicated - should be corrected, but I would prefer to do it with the final release, and possibly split the table into 2 tables for request and response parameters in the next version of Commonalities. It would be good to have the input from @bigludo7 for that. My initial proposal for attribute description: `"Date when the event subscription has started. This attribute must be present in the response when subscription creation process is completed"`
> 
> The rationale for changing `startsAt` to optional in `Subscription` component is the asynchronous subscription creation , when its starting moment is not known yet (#262). It should be decided by subprojects if the asynchronous case is covered by the API.

It is fine to wait to Ludovic for the API design guidelines, and fine to have for final Commonalities Release v0.4.0.

Indeed i like more your proposal Rafal for the wording:

> "Date when the event subscription has started. This attribute must be present in the response when subscription creation process is completed"

2024-08-07 09:30 UTC, PedroDiez approved these changes
LGTM

2024-08-07 09:31 UTC, rartych commented
> Line 453: Spectral warning, "`Event-typeNotification` should be pascal case (UpperCamelCase)"

Corrected by https://github.com/rartych/Commonalities/commit/52d754e3f9e938679eef69e8affd431e50610e68

2024-08-07 09:44 UTC, shilpa-padgaonkar approved these changes
/LGTM

2024-08-07 14:18 UTC, PedroDiez commented
Merging this PR as having 2 approvals an Patrice is on holidays.

Let's followUp this [comment](https://github.com/camaraproject/Commonalities/pull/267#pullrequestreview-2221460283) by Kevin within #243

2024-08-07 14:18 UTC, merged